#%RAML 1.0 NamedExample
value:
  -
    type_data:
      account_type: "checking"
    base_data:
      account_alias: "Joint Household Account"
      account_number: "123456"
      account_status: "active"
  -
    type_data:
      account_type: "checking"
    base_data:
      account_alias: "Joint Household Account"
      account_number: "123456"
      account_status: "active"
