#%RAML 1.0 DataType

displayName: Account Description
description: Friendly user designated name, making it easier to identifying accounts. 
required: true
type: string
maxLength: 25
examples:
  checking: "Joint Household Account"
  savings: "Summer Holiday Provision"
  investment: "Retirement Funds"
