#%RAML 1.0 DataType

displayName: Name
description: First and Lastname of a person
type: object
properties:
  firstname:
    displayName: First Name
    description: First name of the user
    required: true
    type: string
  lastname:
    displayName: Last Name
    description: Last name of the user
    required: true
    type: string
